name: Scrape API, Fetch Weather, and Update CSV

on:
  schedule:
    - cron: "*/10 22-23 * * *"
    - cron: "*/10 0-13 * * *"
    - cron: "0-59/10 23 * * *"

jobs:
  run_scrape_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3  # Replace with your Python version if necessary

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python test_baby.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Jingkhailim"
          git config --global user.email "jingkhai.lim@outlook.com"
          git add .
          git commit -m "Update CSV file"
          git push
