name: Scrape API, Fetch Weather, and Update CSV

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run_scrape_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Rest of your steps...
